# This file should not be used in deployed environments. Instead, set
# the SETTINGS_PATH environment variable to point to a configuration
# file that contains these settings.


services:
- name: 3scales-amp
  id: 3101b971-1044-4816-a7ac-9ded2e028079
  description: 3scales-amp service for secure RESTful services
  tags:
    - 3scales
  metadata:
    provider:
      name:
    listing:
      imageUrl: ~
      blurb: 3scales-amp service for secure RESTful services
  plans:
  - name: testPlan
    id: 2451fa22-df16-4c10-ba6e-1f682d3dcdc9
    description: testPlan desc
    metadata:
      cost: 0.0
      bullets:
      - content: test content 1
      - content: test content 2
      - content: test content 3

